apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-api
  namespace: aegis-system
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-operator-ui
  namespace: aegis-system
spec:
  replicas: 1
