"""Pure domain types and transitions.

This package must not import infrastructure, network clients, or framework code.
"""

from aegis_agent_platform.domain.events import (
    ActorKind,
    ActorReference,
    DomainEventType,
    EventEnvelope,
    JsonValue,
    TraceContext,
)
from aegis_agent_platform.domain.model import (
    ContentKind,
    ContentPart,
    FinishReason,
    ImagePart,
    JsonSchema,
    MessageRole,
    ModelCapabilities,
    ModelErrorClass,
    ModelGatewayError,
    ModelIdentity,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    PricingVersion,
    ProviderIdentity,
    SafetyOutcome,
    SafetyResult,
    TextPart,
    TokenUsage,
    ToolCallPart,
    ToolCallProposal,
    ToolDefinition,
    ToolResultPart,
)
from aegis_agent_platform.domain.work import (
    FailureClass,
    WorkLease,
    WorkRequest,
    WorkStatus,
    WorkTransition,
    next_status,
)

__all__ = [
    "ActorKind",
    "ActorReference",
    "ContentKind",
    "ContentPart",
    "DomainEventType",
    "EventEnvelope",
    "FailureClass",
    "FinishReason",
    "ImagePart",
    "JsonSchema",
    "JsonValue",
    "MessageRole",
    "ModelCapabilities",
    "ModelErrorClass",
    "ModelGatewayError",
    "ModelIdentity",
    "ModelMessage",
    "ModelRequest",
    "ModelResponse",
    "PricingVersion",
    "ProviderIdentity",
    "SafetyOutcome",
    "SafetyResult",
    "TextPart",
    "TokenUsage",
    "ToolCallPart",
    "ToolCallProposal",
    "ToolDefinition",
    "ToolResultPart",
    "TraceContext",
    "WorkLease",
    "WorkRequest",
    "WorkStatus",
    "WorkTransition",
    "next_status",
]
