apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: aegis-control-plane
    newName: ghcr.io/mrinmoyece/aegis-agent-platform
    digest: sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
  - name: aegis-operator-ui
    newName: ghcr.io/mrinmoyece/aegis-operator-ui
    digest: sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
  - name: otel/opentelemetry-collector-contrib
    newName: otel/opentelemetry-collector-contrib
    digest: sha256:9c247564e65ca19f97d891cca19a1a8d291ce631b890885b44e3503c5fdb3895
